### ISSUE TITLE
Error trying to instantiate any object: self is not defined

### ISSUE THREAD

**Issue by mihoward21** [gnosis/safe-apps-sdk#292]
Hi, I'm trying to follow [the instructions](https://github.com/gnosis/safe-apps-sdk/tree/master/packages/safe-apps-web3-react) in the readme for the web3-react connector but I keep getting this error:

```
ReferenceError: self is not defined
    at Object.<anonymous> (/Users/mike/Repos/splits/node_modules/@gnosis.pm/safe-react-gateway-sdk/dist/index.min.js:1:258)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/mike/Repos/splits/node_modules/@gnosis.pm/safe-apps-sdk/dist/src/types/gateway.js:4:32)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
```

The error comes up just when I try to instantiate the connector: `const safeMultisigConnector = new SafeAppConnector()`

I've tried following [the instructions](https://github.com/gnosis/safe-apps-sdk/tree/master/packages/safe-apps-provider) for the more generic provider, but get the same error in there too.

Any guidance would be appreciated. I did create a fresh app using the [cra-template-safe-app](https://github.com/gnosis/safe-apps-sdk/tree/master/packages/cra-template-safe-app) and that works, though that's not feasible for me. If I'm going to use safe app I need to be able to add it to an existing project. It's a react app running on nextjs. I'm wondering if something about nextjs is causing the issue, but I haven't had time to dig into that.

**Comment by yagopv** [comment]
Hey @mihoward21. I created a repo for testing the problem 

https://github.com/yagopv/web3-safe-connector-sample

But seems to work just fine

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/1576776/154984388-e79c7f7a-fd49-4633-b829-dfa3ce664e24.png">

Could you share your code ? What versions are you using ?

**Comment by yagopv** [comment]
Aaah yes. I created a nextjs project and I could reproduce it there. Let me dig in then but seems nextjs related

**Comment by yagopv** [comment]
Hey, found the problem @mihoward21. Basically the issue is with nextjs using server side rendering. One of our libraries is trusting the `window` object (compiled `self`) so when nextjs tries to render in the server it fails as `window` does not exist on that context.

For a workaround you can take a look again to this repo:

https://github.com/yagopv/web3-safe-connector-sample

I updated the example to a nextjs application and what I'm doing is dynamically loading a component with the safe info and with SSR disabled (`<SafeInfo />`). This way I'm ensuring nextjs only try to use our libraries client side.

You can do something similar to this to continue working on your project but anyway we would take a look internally. (@dasanra)

Thanks for the catch!

**Comment by mihoward21** [comment]
@yagopv thank you for the workaround! I'll try that out.

**Comment by sakulstra** [comment]
@yagopv any chance of this being fixed on the dependency? The dynamic import path is quite expensive & cumbersome when using multiple providers. Which dependency is the issue here?

**Comment by mikheevm** [comment]
@yagopv could you share the code which uses window? usually, we add a check for the window to make it compatible with SSR

**Comment by sakulstra** [comment]
@mikheevm it seems like importing without shaking is enough
```
import { SafeAppConnector } from '@gnosis.pm/safe-apps-web3-react';
```
we then use `SafeAppConnector` within a `useEffect` call down the road.

**Comment by yagopv** [comment]
Hey, just read about this, yesterday I was off 😬

But @sakulstra, the `self` error is not happening anymore? that's strange. I think we have an issue for SSR in our https://github.com/gnosis/safe-react-gateway-sdk package as when we build it there is a `self` reference in the resulting index.min.js. That's causing the self not defined error.

If we change the webpack config for adding a `globalThis: 'this'` then the resulting compilation changes `self` for `this` and the error is not happening anymore. You will find then the `window` error one if you initialize the connector outside the browser context ... but as you said if the initialization happen inside an useEffect nextjs seems to be forced to use it in the browser environment

@mikheevm what do you think about the globalThis option? I think we can add it

**Comment by yagopv** [comment]
Hey @mihoward21 , @sakulstra . We made some changes in our SDK's for making them more compatible with SSR solutions so [the latest version](https://www.npmjs.com/package/@gnosis.pm/safe-apps-web3-react/v/1.2.0) of the connector, should work 

As an example using NextJS [this repo](https://github.com/yagopv/web3-safe-connector-sample)
